ARG KEYCLOAK_VERSION=26.6.1

FROM eclipse-temurin:25-jre AS jre
FROM quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}

USER root
COPY --from=jre /opt/java/openjdk /opt/java/openjdk
ENV JAVA_HOME=/opt/java/openjdk
ENV PATH=/opt/java/openjdk/bin:$PATH
USER 1000
